### ISSUE TITLE
synx error happens

### ISSUE THREAD

**Issue by jkyin** [venmo/synx#134]
I run this command `synx -p --no-sort-by-name foo.xcodeproj`. And here is the log.

```
/Users/Yin/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate synx-0.2.1, because clamp-1.1.2 conflicts with clamp (~> 0.6) (Gem::ConflictError)
	from /Users/Yin/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /Users/Yin/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /Users/Yin/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /Users/Yin/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /Users/Yin/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/Yin/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/synx-0.2.1/bin/synx:4:in `<top (required)>'
	from /Users/Yin/.rbenv/versions/2.3.3/bin/synx:22:in `load'
	from /Users/Yin/.rbenv/versions/2.3.3/bin/synx:22:in `<main>'
```

**Comment by nalexander50** [comment]
I had the same problem after running a `gem update`. To resolve the issue, you can uninstall the updated version of clamp and re-install an older version. Keep in mind, this may break other applications elsewhere. I don't actually know what the clamp gem does.

`gem uninstall clamp -v 1.2.1`
`gem install clamp -v 0.6.5`
