### ISSUE TITLE
The plist file at path doesn't exist.

### ISSUE THREAD

**Issue by wongzigii** [venmo/synx#93]
I am trying to synx a `xcworkspace` project .

Terminal Output:
    
     /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:64:in `read': [!] The plist file at path `/Users/Wongzigii/QuQQi-OneYuan/QuQQi-OneYuan/QuQQi-OneYuan.xcworkspace/project.pbxproj` doesn't exist. (Xcodeproj::Informative)

	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:13:in `read_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:193:in `initialize_from_file'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:95:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/synx-0.1.1/bin/synx:23:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from /Library/Ruby/Gems/2.0.0/gems/synx-0.1.1/bin/synx:6:in `<top (required)>'
	from /usr/local/bin/synx:23:in `load'
	from /usr/local/bin/synx:23:in `<main>'

Any idea how to fix it ?

**Comment by dzmitry-sazanovich-epam** [comment]
The same problem

**Comment by nico75005** [comment]
Instead of `synx your_project_path` try `synx your_project_path/project_name.xcodeproj`

**Comment by marklarr** [comment]
@dzmitry-sazanovich-epam @wongzigii, did @nico75005's suggestion fix your issue?

**Comment by wongzigii** [comment]
@marklarr It doesn't work for me. Unfortunately.

**Comment by daviskoh** [comment]
+1

**Comment by StevenVerheyen** [comment]
Suggested comment of @nico75005 is working for me 👍
